# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 10 Aug 2015 10:18:52 +0000
*               @ALL          1
*               @user         8
