<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 11 Aug 2015 15:17:37 +0200
 */

$conf['title'] = 'Аналитика';
$conf['start'] = 'index';
$conf['lang'] = 'ru';
$conf['tagline'] = 'Познание актуальной реальности через факты...';
$conf['license'] = 'publicdomain';
$conf['deaccent'] = '2';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['fnencode'] = 'safe';

//Changes for public web-site:
//$conf['userewrite'] = 1;
//$conf['useslash'] = 1;

// end auto-generated content
