<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 22 Sep 2015 11:41:47 +0200
 */

$conf['title'] = 'Аналитика';
$conf['start'] = 'index';
$conf['lang'] = 'ru';
$conf['tagline'] = 'Познание актуальной реальности через факты...';
$conf['license'] = 'publicdomain';
$conf['deaccent'] = '2';
$conf['youarehere'] = 1;
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['fnencode'] = 'safe';
$conf['plugin']['revealjs']['controls'] = 1;
$conf['plugin']['revealjs']['build_all_lists'] = 1;
$conf['plugin']['revealjs']['show_progress_bar'] = 1;

// end auto-generated content
